/* USE eloyals; */

/* tbl_contry */
INSERT INTO tbl_country ( name ) VALUES ( "Afghanistan");
INSERT INTO tbl_country ( name ) VALUES ( "Albania");
INSERT INTO tbl_country ( name ) VALUES ( "Algeria");
INSERT INTO tbl_country ( name ) VALUES ( "Andorra");
INSERT INTO tbl_country ( name ) VALUES ( "Angola");
INSERT INTO tbl_country ( name ) VALUES ( "Antigua & Deps");
INSERT INTO tbl_country ( name ) VALUES ( "Argentina");
INSERT INTO tbl_country ( name ) VALUES ( "Armenia");
INSERT INTO tbl_country ( name ) VALUES ( "Australia");
INSERT INTO tbl_country ( name ) VALUES ( "Austria");
INSERT INTO tbl_country ( name ) VALUES ( "Azerbaijan");
INSERT INTO tbl_country ( name ) VALUES ( "Bahamas");
INSERT INTO tbl_country ( name ) VALUES ( "Bahrain");
INSERT INTO tbl_country ( name ) VALUES ( "Bangladesh");
INSERT INTO tbl_country ( name ) VALUES ( "Barbados");
INSERT INTO tbl_country ( name ) VALUES ( "Belarus");
INSERT INTO tbl_country ( name ) VALUES ( "Belgium");
INSERT INTO tbl_country ( name ) VALUES ( "Belize");
INSERT INTO tbl_country ( name ) VALUES ( "Benin");
INSERT INTO tbl_country ( name ) VALUES ( "Bhutan");
INSERT INTO tbl_country ( name ) VALUES ( "Bolivia");
INSERT INTO tbl_country ( name ) VALUES ( "Bosnia Herzegovina");
INSERT INTO tbl_country ( name ) VALUES ( "Botswana");
INSERT INTO tbl_country ( name ) VALUES ( "Brazil");
INSERT INTO tbl_country ( name ) VALUES ( "Brunei");
INSERT INTO tbl_country ( name ) VALUES ( "Bulgaria");
INSERT INTO tbl_country ( name ) VALUES ( "Burkina");
INSERT INTO tbl_country ( name ) VALUES ( "Burundi");
INSERT INTO tbl_country ( name ) VALUES ( "Cambodia");
INSERT INTO tbl_country ( name ) VALUES ( "Cameroon");
INSERT INTO tbl_country ( name ) VALUES ( "Canada");
INSERT INTO tbl_country ( name ) VALUES ( "Cape Verde");
INSERT INTO tbl_country ( name ) VALUES ( "Central African Rep");
INSERT INTO tbl_country ( name ) VALUES ( "Chad");
INSERT INTO tbl_country ( name ) VALUES ( "Chile");
INSERT INTO tbl_country ( name ) VALUES ( "China");
INSERT INTO tbl_country ( name ) VALUES ( "Colombia");
INSERT INTO tbl_country ( name ) VALUES ( "Comoros");
INSERT INTO tbl_country ( name ) VALUES ( "Congo");
INSERT INTO tbl_country ( name ) VALUES ( "Congo {Democratic Rep}");
INSERT INTO tbl_country ( name ) VALUES ( "Costa Rica");
INSERT INTO tbl_country ( name ) VALUES ( "Croatia");
INSERT INTO tbl_country ( name ) VALUES ( "Cuba");
INSERT INTO tbl_country ( name ) VALUES ( "Cyprus");
INSERT INTO tbl_country ( name ) VALUES ( "Czech Republic");
INSERT INTO tbl_country ( name ) VALUES ( "Denmark");
INSERT INTO tbl_country ( name ) VALUES ( "Djibouti");
INSERT INTO tbl_country ( name ) VALUES ( "Dominica");
INSERT INTO tbl_country ( name ) VALUES ( "Dominican Republic");
INSERT INTO tbl_country ( name ) VALUES ( "East Timor");
INSERT INTO tbl_country ( name ) VALUES ( "Ecuador");
INSERT INTO tbl_country ( name ) VALUES ( "Egypt");
INSERT INTO tbl_country ( name ) VALUES ( "El Salvador");
INSERT INTO tbl_country ( name ) VALUES ( "Equatorial Guinea");
INSERT INTO tbl_country ( name ) VALUES ( "Eritrea");
INSERT INTO tbl_country ( name ) VALUES ( "Estonia");
INSERT INTO tbl_country ( name ) VALUES ( "Ethiopia");
INSERT INTO tbl_country ( name ) VALUES ( "Fiji");
INSERT INTO tbl_country ( name ) VALUES ( "Finland");
INSERT INTO tbl_country ( name ) VALUES ( "France");
INSERT INTO tbl_country ( name ) VALUES ( "Gabon");
INSERT INTO tbl_country ( name ) VALUES ( "Gambia");
INSERT INTO tbl_country ( name ) VALUES ( "Georgia");
INSERT INTO tbl_country ( name ) VALUES ( "Germany");
INSERT INTO tbl_country ( name ) VALUES ( "Ghana");
INSERT INTO tbl_country ( name ) VALUES ( "Greece");
INSERT INTO tbl_country ( name ) VALUES ( "Grenada");
INSERT INTO tbl_country ( name ) VALUES ( "Guatemala");
INSERT INTO tbl_country ( name ) VALUES ( "Guinea");
INSERT INTO tbl_country ( name ) VALUES ( "Guinea-Bissau");
INSERT INTO tbl_country ( name ) VALUES ( "Guyana");
INSERT INTO tbl_country ( name ) VALUES ( "Haiti");
INSERT INTO tbl_country ( name ) VALUES ( "Honduras");
INSERT INTO tbl_country ( name ) VALUES ( "Hungary");
INSERT INTO tbl_country ( name ) VALUES ( "Iceland");
INSERT INTO tbl_country ( name ) VALUES ( "India");
INSERT INTO tbl_country ( name ) VALUES ( "Indonesia");
INSERT INTO tbl_country ( name ) VALUES ( "Iran");
INSERT INTO tbl_country ( name ) VALUES ( "Iraq");
INSERT INTO tbl_country ( name ) VALUES ( "Ireland {Republic}");
INSERT INTO tbl_country ( name ) VALUES ( "Israel");
INSERT INTO tbl_country ( name ) VALUES ( "Italy");
INSERT INTO tbl_country ( name ) VALUES ( "Ivory Coast");
INSERT INTO tbl_country ( name ) VALUES ( "Jamaica");
INSERT INTO tbl_country ( name ) VALUES ( "Japan");
INSERT INTO tbl_country ( name ) VALUES ( "Jordan");
INSERT INTO tbl_country ( name ) VALUES ( "Kazakhstan");
INSERT INTO tbl_country ( name ) VALUES ( "Kenya");
INSERT INTO tbl_country ( name ) VALUES ( "Kiribati");
INSERT INTO tbl_country ( name ) VALUES ( "Korea North");
INSERT INTO tbl_country ( name ) VALUES ( "Korea South");
INSERT INTO tbl_country ( name ) VALUES ( "Kosovo");
INSERT INTO tbl_country ( name ) VALUES ( "Kuwait");
INSERT INTO tbl_country ( name ) VALUES ( "Kyrgyzstan");
INSERT INTO tbl_country ( name ) VALUES ( "Laos");
INSERT INTO tbl_country ( name ) VALUES ( "Latvia");
INSERT INTO tbl_country ( name ) VALUES ( "Lebanon");
INSERT INTO tbl_country ( name ) VALUES ( "Lesotho");
INSERT INTO tbl_country ( name ) VALUES ( "Liberia");
INSERT INTO tbl_country ( name ) VALUES ( "Libya");
INSERT INTO tbl_country ( name ) VALUES ( "Liechtenstein");
INSERT INTO tbl_country ( name ) VALUES ( "Lithuania");
INSERT INTO tbl_country ( name ) VALUES ( "Luxembourg");
INSERT INTO tbl_country ( name ) VALUES ( "Macedonia");
INSERT INTO tbl_country ( name ) VALUES ( "Madagascar");
INSERT INTO tbl_country ( name ) VALUES ( "Malawi");
INSERT INTO tbl_country ( name ) VALUES ( "Malaysia");
INSERT INTO tbl_country ( name ) VALUES ( "Maldives");
INSERT INTO tbl_country ( name ) VALUES ( "Mali");
INSERT INTO tbl_country ( name ) VALUES ( "Malta");
INSERT INTO tbl_country ( name ) VALUES ( "Marshall Islands");
INSERT INTO tbl_country ( name ) VALUES ( "Mauritania");
INSERT INTO tbl_country ( name ) VALUES ( "Mauritius");
INSERT INTO tbl_country ( name ) VALUES ( "Mexico");
INSERT INTO tbl_country ( name ) VALUES ( "Micronesia");
INSERT INTO tbl_country ( name ) VALUES ( "Moldova");
INSERT INTO tbl_country ( name ) VALUES ( "Monaco");
INSERT INTO tbl_country ( name ) VALUES ( "Mongolia");
INSERT INTO tbl_country ( name ) VALUES ( "Montenegro");
INSERT INTO tbl_country ( name ) VALUES ( "Morocco");
INSERT INTO tbl_country ( name ) VALUES ( "Mozambique");
INSERT INTO tbl_country ( name ) VALUES ( "Myanmar, {Burma}");
INSERT INTO tbl_country ( name ) VALUES ( "Namibia");
INSERT INTO tbl_country ( name ) VALUES ( "Nauru");
INSERT INTO tbl_country ( name ) VALUES ( "Nepal");
INSERT INTO tbl_country ( name ) VALUES ( "Netherlands");
INSERT INTO tbl_country ( name ) VALUES ( "New Zealand");
INSERT INTO tbl_country ( name ) VALUES ( "Nicaragua");
INSERT INTO tbl_country ( name ) VALUES ( "Niger");
INSERT INTO tbl_country ( name ) VALUES ( "Nigeria");
INSERT INTO tbl_country ( name ) VALUES ( "Norway");
INSERT INTO tbl_country ( name ) VALUES ( "Oman");
INSERT INTO tbl_country ( name ) VALUES ( "Pakistan");
INSERT INTO tbl_country ( name ) VALUES ( "Palau");
INSERT INTO tbl_country ( name ) VALUES ( "Panama");
INSERT INTO tbl_country ( name ) VALUES ( "Papua New Guinea");
INSERT INTO tbl_country ( name ) VALUES ( "Paraguay");
INSERT INTO tbl_country ( name ) VALUES ( "Peru");
INSERT INTO tbl_country ( name ) VALUES ( "Philippines");
INSERT INTO tbl_country ( name ) VALUES ( "Poland");
INSERT INTO tbl_country ( name ) VALUES ( "Portugal");
INSERT INTO tbl_country ( name ) VALUES ( "Qatar");
INSERT INTO tbl_country ( name ) VALUES ( "Romania");
INSERT INTO tbl_country ( name ) VALUES ( "Russian Federation");
INSERT INTO tbl_country ( name ) VALUES ( "Rwanda");
INSERT INTO tbl_country ( name ) VALUES ( "St Kitts & Nevis");
INSERT INTO tbl_country ( name ) VALUES ( "St Lucia");
INSERT INTO tbl_country ( name ) VALUES ( "Saint Vincent & the Grenadines");
INSERT INTO tbl_country ( name ) VALUES ( "Samoa");
INSERT INTO tbl_country ( name ) VALUES ( "San Marino");
INSERT INTO tbl_country ( name ) VALUES ( "Sao Tome & Principe");
INSERT INTO tbl_country ( name ) VALUES ( "Saudi Arabia");
INSERT INTO tbl_country ( name ) VALUES ( "Senegal");
INSERT INTO tbl_country ( name ) VALUES ( "Serbia");
INSERT INTO tbl_country ( name ) VALUES ( "Seychelles");
INSERT INTO tbl_country ( name ) VALUES ( "Sierra Leone");
INSERT INTO tbl_country ( name ) VALUES ( "Singapore");
INSERT INTO tbl_country ( name ) VALUES ( "Slovakia");
INSERT INTO tbl_country ( name ) VALUES ( "Slovenia");
INSERT INTO tbl_country ( name ) VALUES ( "Solomon Islands");
INSERT INTO tbl_country ( name ) VALUES ( "Somalia");
INSERT INTO tbl_country ( name ) VALUES ( "South Africa");
INSERT INTO tbl_country ( name ) VALUES ( "South Sudan");
INSERT INTO tbl_country ( name ) VALUES ( "Spain");
INSERT INTO tbl_country ( name ) VALUES ( "Sri Lanka");
INSERT INTO tbl_country ( name ) VALUES ( "Sudan");
INSERT INTO tbl_country ( name ) VALUES ( "Suriname");
INSERT INTO tbl_country ( name ) VALUES ( "Swaziland");
INSERT INTO tbl_country ( name ) VALUES ( "Sweden");
INSERT INTO tbl_country ( name ) VALUES ( "Switzerland");
INSERT INTO tbl_country ( name ) VALUES ( "Syria");
INSERT INTO tbl_country ( name ) VALUES ( "Taiwan");
INSERT INTO tbl_country ( name ) VALUES ( "Tajikistan");
INSERT INTO tbl_country ( name ) VALUES ( "Tanzania");
INSERT INTO tbl_country ( name ) VALUES ( "Thailand");
INSERT INTO tbl_country ( name ) VALUES ( "Togo");
INSERT INTO tbl_country ( name ) VALUES ( "Tonga");
INSERT INTO tbl_country ( name ) VALUES ( "Trinidad & Tobago");
INSERT INTO tbl_country ( name ) VALUES ( "Tunisia");
INSERT INTO tbl_country ( name ) VALUES ( "Turkey");
INSERT INTO tbl_country ( name ) VALUES ( "Turkmenistan");
INSERT INTO tbl_country ( name ) VALUES ( "Tuvalu");
INSERT INTO tbl_country ( name ) VALUES ( "Uganda");
INSERT INTO tbl_country ( name ) VALUES ( "Ukraine");
INSERT INTO tbl_country ( name ) VALUES ( "United Arab Emirates");
INSERT INTO tbl_country ( name ) VALUES ( "United Kingdom");
INSERT INTO tbl_country ( name ) VALUES ( "United States");
INSERT INTO tbl_country ( name ) VALUES ( "Uruguay");
INSERT INTO tbl_country ( name ) VALUES ( "Uzbekistan");
INSERT INTO tbl_country ( name ) VALUES ( "Vanuatu");
INSERT INTO tbl_country ( name ) VALUES ( "Vatican City");
INSERT INTO tbl_country ( name ) VALUES ( "Venezuela");
INSERT INTO tbl_country ( name ) VALUES ( "Vietnam");
INSERT INTO tbl_country ( name ) VALUES ( "Yemen");
INSERT INTO tbl_country ( name ) VALUES ( "Zambia");
INSERT INTO tbl_country ( name ) VALUES ( "Zimbabwe");

/* tbl_county */
INSERT INTO tbl_county (name) VALUES ('Carlow');
INSERT INTO tbl_county (name) VALUES ('Cavan');
INSERT INTO tbl_county (name) VALUES ('Clare');
INSERT INTO tbl_county (name) VALUES ('Cork');
INSERT INTO tbl_county (name) VALUES ('Donegal');
INSERT INTO tbl_county (name) VALUES ('Dublin');
INSERT INTO tbl_county (name) VALUES ('Galway');
INSERT INTO tbl_county (name) VALUES ('Kerry');
INSERT INTO tbl_county (name) VALUES ('Kildare');
INSERT INTO tbl_county (name) VALUES ('Kilkenny');
INSERT INTO tbl_county (name) VALUES ('Laois');
INSERT INTO tbl_county (name) VALUES ('Leitrim');
INSERT INTO tbl_county (name) VALUES ('Limerick');
INSERT INTO tbl_county (name) VALUES ('Longford');
INSERT INTO tbl_county (name) VALUES ('Louth');
INSERT INTO tbl_county (name) VALUES ('Mayo');
INSERT INTO tbl_county (name) VALUES ('Meath');
INSERT INTO tbl_county (name) VALUES ('Monaghan');
INSERT INTO tbl_county (name) VALUES ('Offaly');
INSERT INTO tbl_county (name) VALUES ('Roscommon');
INSERT INTO tbl_county (name) VALUES ('Sligo');
INSERT INTO tbl_county (name) VALUES ('Tipperary');
INSERT INTO tbl_county (name) VALUES ('Waterford');
INSERT INTO tbl_county (name) VALUES ('Westmeath');
INSERT INTO tbl_county (name) VALUES ('Wexford');
INSERT INTO tbl_county (name) VALUES ('Wicklow');

/* tbl_category */
INSERT INTO tbl_category ( name ) VALUES ( "Coffee Shop / House");

/* tbl_package */
INSERT INTO tbl_package ( name, price ) VALUES ( "Standard", 100.00 );

/* tbl_customer */
INSERT INTO tbl_customer ( id, email, password, first_name, last_name, country_id, county_id ) VALUES (1158, "senna@test.com","test","Airton","Senna",6,6); 
INSERT INTO tbl_customer ( id, email, password, first_name, last_name, country_id, county_id ) VALUES (4337, "aoife@test.com","test","Aoife","O'Shea",56,6);
INSERT INTO tbl_customer ( id, email, password, first_name, last_name, country_id, county_id ) VALUES (7719, "brian@test.com","test","Brian","O'Driscol",97,6);
INSERT INTO tbl_customer ( id, email, password, first_name, last_name, country_id, county_id ) VALUES (8639, "lana@test.com","test","Lana","Del Rey",100,6);

/* tbl_business */
INSERT INTO tbl_business ( username, password, email, package_id, category_id ) VALUES ( "cct", "test", "cct@cct.ie", 1, 1);
INSERT INTO tbl_business ( username, password, email, package_id, category_id ) VALUES ( "wg", "test", "wg@wg.ie", 1, 1);
INSERT INTO tbl_business ( username, password, email, package_id, category_id ) VALUES ( "fixx", "test", "fixx@fixx.ie", 1, 1);
INSERT INTO tbl_business ( username, password, email, package_id, category_id ) VALUES ( "5ive", "test", "5ive@5ive.ie", 1, 1);

/* tbl_user */
INSERT INTO tbl_user ( username, name, password, admin, business_id ) VALUES ( "cct", "cct", "test", 1, 1 );
INSERT INTO tbl_user ( username, name, password, admin, business_id ) VALUES ( "wg", "WG", "test", 1, 2 );
INSERT INTO tbl_user ( username, name, password, admin, business_id ) VALUES ( "fixx", "Fixx", "test", 1, 3 );
INSERT INTO tbl_user ( username, name, password, admin, business_id ) VALUES ( "5five", "5ive", "test", 1, 4 );

/* tbl_unit */
INSERT INTO tbl_unit ( sing_descr, plur_descr ) VALUES ("Stamp", "Stamps");

/* tbl_bus_item */
INSERT INTO tbl_bus_item ( business_id, id, description, unit_id, convert_rate ) VALUES (1, "Coffee", "Cup of Coffee", 1, 9);
INSERT INTO tbl_bus_item ( business_id, id, description, unit_id, convert_rate ) VALUES (1, "Cake", "Slice of Cake", 1, 9);
INSERT INTO tbl_bus_item ( business_id, id, description, unit_id, convert_rate ) VALUES (1, "Juice", "Juice", 1, 9);
INSERT INTO tbl_bus_item ( business_id, id, description, unit_id, convert_rate ) VALUES (1, "Muffin", "Muffin", 1, 9);
INSERT INTO tbl_bus_item ( business_id, id, description, unit_id, convert_rate ) VALUES (2, "Coffee", "Cup of Coffee", 1, 8);
INSERT INTO tbl_bus_item ( business_id, id, description, unit_id, convert_rate ) VALUES (3, "Coffee", "Cup of Coffee", 1, 4);
INSERT INTO tbl_bus_item ( business_id, id, description, unit_id, convert_rate ) VALUES (4, "Coffee", "Cup of Coffee", 1, 9);

/* tbl_cus_item */
INSERT INTO tbl_cus_item ( customer_id, business_id, item_id, balance, reward ) VALUES ( 4337, 1, "Coffee", 3, 1);
INSERT INTO tbl_cus_item ( customer_id, business_id, item_id, balance, reward ) VALUES ( 4337, 1, "Cake", 0, 2);
INSERT INTO tbl_cus_item ( customer_id, business_id, item_id, balance, reward ) VALUES ( 4337, 1, "Muffin", 8, 0);